
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label label2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Entry iBroj1;

	private global::Gtk.Entry iBroj2;

	private global::Gtk.Entry iBroj3;

	private global::Gtk.Entry iBroj4;

	private global::Gtk.Entry iBroj5;

	private global::Gtk.Entry iBroj6;

	private global::Gtk.Label label1;

	private global::Gtk.Label lBrojevi;

	private global::Gtk.Label lStatus;

	private global::Gtk.Button button1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Loto 6 od 45");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(20));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Unesi brojeve");
		this.vbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
		w1.Position = 0;
		w1.Padding = ((uint)(20));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 20;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj1 = new global::Gtk.Entry();
		this.iBroj1.WidthRequest = 50;
		this.iBroj1.HeightRequest = 80;
		this.iBroj1.CanFocus = true;
		this.iBroj1.Name = "iBroj1";
		this.iBroj1.IsEditable = true;
		this.iBroj1.MaxLength = 2;
		this.iBroj1.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj1]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj2 = new global::Gtk.Entry();
		this.iBroj2.WidthRequest = 50;
		this.iBroj2.HeightRequest = 80;
		this.iBroj2.CanFocus = true;
		this.iBroj2.Name = "iBroj2";
		this.iBroj2.IsEditable = true;
		this.iBroj2.MaxLength = 2;
		this.iBroj2.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj2]));
		w3.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj3 = new global::Gtk.Entry();
		this.iBroj3.WidthRequest = 50;
		this.iBroj3.HeightRequest = 80;
		this.iBroj3.CanFocus = true;
		this.iBroj3.Name = "iBroj3";
		this.iBroj3.IsEditable = true;
		this.iBroj3.MaxLength = 2;
		this.iBroj3.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj3]));
		w4.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj4 = new global::Gtk.Entry();
		this.iBroj4.WidthRequest = 50;
		this.iBroj4.HeightRequest = 80;
		this.iBroj4.CanFocus = true;
		this.iBroj4.Name = "iBroj4";
		this.iBroj4.IsEditable = true;
		this.iBroj4.MaxLength = 2;
		this.iBroj4.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj4]));
		w5.Position = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj5 = new global::Gtk.Entry();
		this.iBroj5.WidthRequest = 50;
		this.iBroj5.HeightRequest = 80;
		this.iBroj5.CanFocus = true;
		this.iBroj5.Name = "iBroj5";
		this.iBroj5.IsEditable = true;
		this.iBroj5.MaxLength = 2;
		this.iBroj5.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj5]));
		w6.Position = 4;
		// Container child hbox1.Gtk.Box+BoxChild
		this.iBroj6 = new global::Gtk.Entry();
		this.iBroj6.WidthRequest = 50;
		this.iBroj6.HeightRequest = 80;
		this.iBroj6.CanFocus = true;
		this.iBroj6.Name = "iBroj6";
		this.iBroj6.IsEditable = true;
		this.iBroj6.MaxLength = 2;
		this.iBroj6.InvisibleChar = '●';
		this.hbox1.Add(this.iBroj6);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.iBroj6]));
		w7.Position = 5;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(20));
		// Container child vbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Izvučeni brojevi");
		this.vbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(20));
		// Container child vbox1.Gtk.Box+BoxChild
		this.lBrojevi = new global::Gtk.Label();
		this.lBrojevi.HeightRequest = 100;
		this.lBrojevi.Name = "lBrojevi";
		this.vbox1.Add(this.lBrojevi);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lBrojevi]));
		w10.Position = 3;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lStatus = new global::Gtk.Label();
		this.lStatus.HeightRequest = 100;
		this.lStatus.Name = "lStatus";
		this.vbox1.Add(this.lStatus);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lStatus]));
		w11.Position = 4;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.HeightRequest = 100;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Pokreni");
		global::Gtk.Image w12 = new global::Gtk.Image();
		w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-play", global::Gtk.IconSize.Menu);
		this.button1.Image = w12;
		this.vbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button1]));
		w13.Position = 5;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1002;
		this.DefaultHeight = 592;
		this.Show();
		this.button1.Clicked += new global::System.EventHandler(this.OnPokreni);
	}
}
